functionsDirectory = "E:\\TITDB\\TITDB\\TITdb\\webclone\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "E:\\TITDB\\TITDB\\TITdb\\webclone\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm install --prefix api && npm install --prefix frontend && npm run build --prefix frontend"
functions = "E:\\TITDB\\TITDB\\TITdb\\webclone\\netlify\\functions"

[build.environment]
DATABASE_URL = "postgres://postgres.pgpvfxagkeexvnmzrsty:MattyMeda890@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]